### ISSUE TITLE
namespace resolving for multiple instances fails

### ISSUE THREAD

**Issue by JoernT** [Jinntec/Fore#84]
for bug reproduction and solution attempt see branch 'test-ling'.

```
<fx-fore>
    <fx-model id="model-1">
        <fx-instance id="default"
                     src="data/default.xml"
                     xpath-default-namespace="http://www.tei-c.org/ns/1.0">
        </fx-instance>

        <fx-instance id="second">
            <data>
                <morpheme/>
            </data>
        </fx-instance>
    </fx-model>

    <main>
        <h2>TEI: {//listChange}</h2>
        <h2>default ns: {instance('second')/morpheme}</h2>
    </main>
</fx-fore>
```

This form demonstrates that two instances cannot working alongside if mixing namespaces with empty namespace addressing. The first value will display while the second is not.

The initial implementation for xpath-default-namespace was placed as an attribute on `fx-fore` which is hardly sufficient if using multiple instances with different namespace or no namespace. The code on the branch tries to solve this by putting the attribute on the respective instance and passing in the instance when calling `evalXXX`.

**Comment by DrRataplan** [comment]
Thinking about this a bit more, I am more confident in the XSLT-like approach of keeping the namespace declarations more local. There is a big downside in moving the namespace declaration to the instance:. The function `fx:instance` needs to be evaluated (aka runtime) while the namespaces already need to be present statically. While in practice it won't happen, in theory you could do something like `instance($instance-name)`: making it even obfuscated where whan namespace declarations come from.

Making this behaviour is relatively straight-forward: take the namespace resolver in https://github.com/Jinntec/Fore/blob/dev/src/xpath-evaluation.js#L35 and get the value of the attribute `xmlns:prefix` of the closest ancestor (from the defining element) . Though HTML is not XML, and strictly speaking xmlns declarations are not attributes per se, this feels more natural. We cannot use XPath for this because even though the xmlns declarations look and feel like attributes, the spec filters m out.

What are your thoughts?

**Comment by JoernT** [comment]
i fear i disagree here cause what i fear is a markup mess.

A very common use cases is a select control getting its values from a different instance than it is bound to. If i get you right that would result in:

```
<fx-control ref="item" xpath-default-namespace="foobar">
  <select ref="instance('thevalues')/option" xpath-default-namespace="">
...
```

Also if using i18n instances the UI the namespace will changed all the time within the markup causing a lot of noise all over the place.

Quite heavy markup IMO - of course that could be stripped a bit but leaves two problems that i don't like:

* using empty namespace requires markup but should be the default
* you potentially have to repeat the `xpath-default-namespace` or at least take extra care in writing the UI.

Actually what is needed is to put an instance into a namespace - as HTML does not know them best we can do is mimic them as we do with the current `xpath-default-namespace` but maybe just `xpath-ns` or even `xml-ns`.

Also semantically i think the evaluation namespace belongs to the instance and binding controls or template expressions shouldn't be required to pick the right namespace up each time. 

Regarding the instance() function - assuming this:
```
<fx-instance id="default" xml-ns="http:foobar.com"'>
<fx-instance id="two">
...
{instance()/aNode}
{instance('two'}
```

Why couldn't we pick up the namespaces at instance init time and them somehow into context for xpath evaluation that won't take place before `rebuild` is running? Couldn't that solve the issue?

Appreciate your comments.

**Comment by DrRataplan** [comment]
The purist in me is yelling to force devs to do exactly what you are
describing: make developers either explicitly state their intent by
sprinkling their namespace declarations around, and maybe sometimes
override them. Or have them use prefixes; in that i18n you are describing,
we'd get something like
***@***.***:key="my_key"]`. In TEI we'd get
`instance('tei-chapter.xml')//tei:hi[ancestor::tei:div][1]/ancestor::tei:title`
or something like that. Very explicit indeed.

But that is annoying and prone to bugs that are a nightmare to try to fix:
no one likes XPaths that just fail to resolve to any nodes. A very correct
but very frustrating API.

The most pragmatic solution is something like this:

- We can parse the query,
- We see which instance function(s) it refers to (hoping it will always
only be one). Throwing when the input to the `instance` function is dynamic
for any reason.
- We couple this query instance to the namespace information present on the
matching `instance`

Feels a bit pragmatic, but it also feels like a good API where most
developers will not be forced to care about namespaces. And I think
(almost) every developer will have something better to do than jumping
through namespace hoops!

What are your thoughts?

Op di 23 nov. 2021 om 11:35 schreef Joern Turner ***@***.***>:

**Comment by JoernT** [comment]
yep - i guess we're on the same planet. A pragmatic approach is important if you want more people aboard in understanding the markup. The whole explicitness is causing a lot of noise and redundant typing and lots of people outright hate prefixes (and i kind of agree ;)

**Comment by JoernT** [comment]
so, in essence this means to make the above markup work right? 

And with regard to instance() i think it's ok to say that it always needs to be a valid idref.

**Comment by DrRataplan** [comment]
I just pushed to the `test-ling` branch with an implementation of what I described earlier today. Some tests are failing though. I'll look at them but feel free to also take a look.

**Comment by JoernT** [comment]
yes - confirm this example to work. However things are more complicated i fear. What is actually is needed is also this to work:

```
 <fx-control ref="//listChange">
            <select ref="instance('second')">
                <template>
                    <option>{item}</option>
                </template>
            </select>
        </fx-control>
```

But this still fails - will have to investigate tomorrow.

**Comment by DrRataplan** [comment]
Good to hear.

That case you mentioned should not be too difficult to address. In the
namespaceresolver I added some defaulting to the 'default' instance. That
should be another instance depending on the intrinsic hierarchy of the
component defining the query. If we can find the correct one (by parsing
that query and looking for calls to 'instance') we should be able to
construct the correct namespaceresolver.

Btw, I did not account for performance yet, first wanted to check to rough
implementation. An easy way to optimize this is to just cache the NS
resolvers by their arguments: at least the query and the defining node.

**Comment by DrRataplan** [comment]
Thanks a lot for that hint! Just made it work! The unit tests are also all succeeding. I hope this helps you out!

I also added some caching because I saw bad performance earlier. I pushed my progress on the `test-ling` branch, which I will PR right now.

**Comment by JoernT** [comment]
guess that's fine now (until we hit another issue ;)

**Comment by DrRataplan** [comment]
Awesome, thanks! Hit me up when the next bug rears its ugly head!
